[package]
name = "rich-sdl2-net-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rich-sdl2-rust = "0.6.4"

[build-dependencies]
bindgen = "0.59.1"
git2 = "0.13.21"
